<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


class CheckTokenRetrieveResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * $checkTokenRetrieve200ApplicationJSONObject
     * 
     * @var ?array<string, mixed> $checkTokenRetrieve200ApplicationJSONObject
     */
	
    public ?array $checkTokenRetrieve200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->checkTokenRetrieve200ApplicationJSONObject = null;
	}
}
