<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


enum EstimatesListEstimateStatus: string
{
    case ESTIMATE_APPROVED = 'ESTIMATE_APPROVED';
    case ESTIMATE_CLOSED = 'ESTIMATE_CLOSED';
    case ESTIMATE_IN_PROGRESS = 'ESTIMATE_IN_PROGRESS';
    case ESTIMATE_OWNER_REJECTED = 'ESTIMATE_OWNER_REJECTED';
    case ESTIMATE_PENDING_ACCEPTANCE = 'ESTIMATE_PENDING_ACCEPTANCE';
    case ESTIMATE_PENDING_APPROVAL = 'ESTIMATE_PENDING_APPROVAL';
    case ESTIMATE_SUBMITTED = 'ESTIMATE_SUBMITTED';
    case ESTIMATE_VENDOR_REJECTED = 'ESTIMATE_VENDOR_REJECTED';
}
