<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


enum ExpenditureListStatus: string
{
    case Approved = 'APPROVED';
    case Billed = 'BILLED';
    case Draft = 'DRAFT';
    case Hold = 'HOLD';
    case InReview = 'IN_REVIEW';
}
