<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class ExpenditureListRequest
{
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     * 
     * @var int $xPmOrg
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Pm-Org')]
    public int $xPmOrg;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__gte,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdGte = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__interval,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdInterval = null;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__lte,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $createdLte = null;
    
    /**
     * Number of results to return per page.
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * The initial index from which to return the results.
     * 
     * @var ?int $offset
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;
    
    /**
     * Which field to use when ordering the results.
     * 
     * @var ?string $ordering
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ordering')]
    public ?string $ordering = null;
    
    /**
     * $status
     * 
     * @var ?array<\PropertyMeld\MeldAPI\Models\Operations\ExpenditureListStatus> $status
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?array $status = null;
    
	public function __construct()
	{
		$this->xPmOrg = 0;
		$this->createdGte = null;
		$this->createdInterval = null;
		$this->createdLte = null;
		$this->limit = null;
		$this->offset = null;
		$this->ordering = null;
		$this->status = null;
	}
}
