<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class InvoiceListRequest
{
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     * 
     * @var int $xPmOrg
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Pm-Org')]
    public int $xPmOrg;
    
    /**
     * created__gte
     * 
     * @var ?string $createdGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__gte')]
    public ?string $createdGte = null;
    
    /**
     * created__interval
     * 
     * @var ?string $createdInterval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__interval')]
    public ?string $createdInterval = null;
    
    /**
     * created__lte
     * 
     * @var ?string $createdLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__lte')]
    public ?string $createdLte = null;
    
    /**
     * declined
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\InvoiceListDeclined $declined
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=declined')]
    public ?InvoiceListDeclined $declined = null;
    
    /**
     * Number of results to return per page.
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * The initial index from which to return the results.
     * 
     * @var ?int $offset
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;
    
    /**
     * Which field to use when ordering the results.
     * 
     * @var ?string $ordering
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ordering')]
    public ?string $ordering = null;
    
    /**
     * paid
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\InvoiceListPaid $paid
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=paid')]
    public ?InvoiceListPaid $paid = null;
    
    /**
     * payment_requested__gte
     * 
     * @var ?string $paymentRequestedGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=payment_requested__gte')]
    public ?string $paymentRequestedGte = null;
    
    /**
     * payment_requested__interval
     * 
     * @var ?string $paymentRequestedInterval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=payment_requested__interval')]
    public ?string $paymentRequestedInterval = null;
    
    /**
     * payment_requested__lte
     * 
     * @var ?string $paymentRequestedLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=payment_requested__lte')]
    public ?string $paymentRequestedLte = null;
    
    /**
     * status
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\InvoiceListStatus $status
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?InvoiceListStatus $status = null;
    
    /**
     * vendor
     * 
     * @var ?string $vendor
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=vendor')]
    public ?string $vendor = null;
    
    /**
     * vendors
     * 
     * @var ?string $vendors
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=vendors')]
    public ?string $vendors = null;
    
	public function __construct()
	{
		$this->xPmOrg = 0;
		$this->createdGte = null;
		$this->createdInterval = null;
		$this->createdLte = null;
		$this->declined = null;
		$this->limit = null;
		$this->offset = null;
		$this->ordering = null;
		$this->paid = null;
		$this->paymentRequestedGte = null;
		$this->paymentRequestedInterval = null;
		$this->paymentRequestedLte = null;
		$this->status = null;
		$this->vendor = null;
		$this->vendors = null;
	}
}
