<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** due_date_choice */
enum MeldListDueDateChoice: string
{
    case OVERDUE = 'overdue';
    case TODAY = 'today';
    case TOMORROW = 'tomorrow';
    case WEEK = 'week';
}
