<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** owner_approval */
enum MeldListOwnerApproval: string
{
    case OwnerApprovalNotRequested = 'OWNER_APPROVAL_NOT_REQUESTED';
    case OwnerApprovalRequested = 'OWNER_APPROVAL_REQUESTED';
    case OwnerApprovalApproved = 'OWNER_APPROVAL_APPROVED';
    case OwnerApprovalNotApproved = 'OWNER_APPROVAL_NOT_APPROVED';
    case OwnerApprovalRequestedEstimates = 'OWNER_APPROVAL_REQUESTED_ESTIMATES';
}
