<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** ack_approval */
enum MeldListAckApproval: string
{
    case TRUE = 'true';
    case FALSE = 'false';
}
