<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** maint_type */
enum MeldListMaintType: string
{
    case ONE = '1';
    case TWO = '2';
}
