<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** Ordering */
enum MeldListOrderBy: string
{
    case OWNER_APPROVAL_REQUEST_DATE = 'owner_approval_request_date';
    case MINUS_OWNER_APPROVAL_REQUEST_DATE = '-owner_approval_request_date';
}
