<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** has_estimates */
enum MeldListHasEstimates: string
{
    case False = 'false';
    case True = 'true';
}
