<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class MeldListRequest
{
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     * 
     * @var int $xPmOrg
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Pm-Org')]
    public int $xPmOrg;
    
    /**
     * ack_approval
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListAckApproval $ackApproval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ack_approval')]
    public ?MeldListAckApproval $ackApproval = null;
    
    /**
     * assigned_to_me
     * 
     * @var ?string $assignedToMe
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=assigned_to_me')]
    public ?string $assignedToMe = null;
    
    /**
     * categories
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListCategories $categories
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=categories')]
    public ?MeldListCategories $categories = null;
    
    /**
     * comments_gte
     * 
     * @var ?string $commentsGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=comments_gte')]
    public ?string $commentsGte = null;
    
    /**
     * comments_lte
     * 
     * @var ?string $commentsLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=comments_lte')]
    public ?string $commentsLte = null;
    
    /**
     * completed__gte
     * 
     * @var ?string $completedGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=completed__gte')]
    public ?string $completedGte = null;
    
    /**
     * completed__interval
     * 
     * @var ?string $completedInterval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=completed__interval')]
    public ?string $completedInterval = null;
    
    /**
     * completed__lte
     * 
     * @var ?string $completedLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=completed__lte')]
    public ?string $completedLte = null;
    
    /**
     * created__gte
     * 
     * @var ?string $createdGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__gte')]
    public ?string $createdGte = null;
    
    /**
     * created__interval
     * 
     * @var ?string $createdInterval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__interval')]
    public ?string $createdInterval = null;
    
    /**
     * created__lte
     * 
     * @var ?string $createdLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__lte')]
    public ?string $createdLte = null;
    
    /**
     * created__offset_lte
     * 
     * @var ?string $createdOffsetLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=created__offset_lte')]
    public ?string $createdOffsetLte = null;
    
    /**
     * due_date_choice
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListDueDateChoice $dueDateChoice
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=due_date_choice')]
    public ?MeldListDueDateChoice $dueDateChoice = null;
    
    /**
     * due_date_gte
     * 
     * @var ?string $dueDateGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=due_date_gte')]
    public ?string $dueDateGte = null;
    
    /**
     * due_date_lte
     * 
     * @var ?string $dueDateLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=due_date_lte')]
    public ?string $dueDateLte = null;
    
    /**
     * ever_been_assigned
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListEverBeenAssigned $everBeenAssigned
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ever_been_assigned')]
    public ?MeldListEverBeenAssigned $everBeenAssigned = null;
    
    /**
     * exp
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListExp $exp
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=exp')]
    public ?MeldListExp $exp = null;
    
    /**
     * exp_s
     * 
     * @var ?string $expS
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=exp_s')]
    public ?string $expS = null;
    
    /**
     * files_gte
     * 
     * @var ?string $filesGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=files_gte')]
    public ?string $filesGte = null;
    
    /**
     * files_lte
     * 
     * @var ?string $filesLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=files_lte')]
    public ?string $filesLte = null;
    
    /**
     * has_estimates
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListHasEstimates $hasEstimates
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=has_estimates')]
    public ?MeldListHasEstimates $hasEstimates = null;
    
    /**
     * invoice_s
     * 
     * @var ?string $invoiceS
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=invoice_s')]
    public ?string $invoiceS = null;
    
    /**
     * Number of results to return per page.
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * maint
     * 
     * @var ?string $maint
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=maint')]
    public ?string $maint = null;
    
    /**
     * maint_type
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListMaintType $maintType
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=maint_type')]
    public ?MeldListMaintType $maintType = null;
    
    /**
     * marked_complete__gte
     * 
     * @var ?string $markedCompleteGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=marked_complete__gte')]
    public ?string $markedCompleteGte = null;
    
    /**
     * marked_complete__interval
     * 
     * @var ?string $markedCompleteInterval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=marked_complete__interval')]
    public ?string $markedCompleteInterval = null;
    
    /**
     * marked_complete__lte
     * 
     * @var ?string $markedCompleteLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=marked_complete__lte')]
    public ?string $markedCompleteLte = null;
    
    /**
     * meldinvoice
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListMeldinvoice $meldinvoice
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=meldinvoice')]
    public ?MeldListMeldinvoice $meldinvoice = null;
    
    /**
     * The initial index from which to return the results.
     * 
     * @var ?int $offset
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;
    
    /**
     * Ordering
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListOrderBy $orderBy
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order_by')]
    public ?MeldListOrderBy $orderBy = null;
    
    /**
     * owner_approval
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListOwnerApproval $ownerApproval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=owner_approval')]
    public ?MeldListOwnerApproval $ownerApproval = null;
    
    /**
     * pg
     * 
     * @var ?string $pg
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pg')]
    public ?string $pg = null;
    
    /**
     * priority
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListPriority $priority
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=priority')]
    public ?MeldListPriority $priority = null;
    
    /**
     * project
     * 
     * @var ?string $project
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=project')]
    public ?string $project = null;
    
    /**
     * project_assigned
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListProjectAssigned $projectAssigned
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=project_assigned')]
    public ?MeldListProjectAssigned $projectAssigned = null;
    
    /**
     * prop
     * 
     * @var ?string $prop
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=prop')]
    public ?string $prop = null;
    
    /**
     * rating
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListRating $rating
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=rating')]
    public ?MeldListRating $rating = null;
    
    /**
     * recurring
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListRecurring $recurring
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=recurring')]
    public ?MeldListRecurring $recurring = null;
    
    /**
     * recurring_meld
     * 
     * @var ?string $recurringMeld
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=recurring_meld')]
    public ?string $recurringMeld = null;
    
    /**
     * remindees
     * 
     * @var ?string $remindees
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=remindees')]
    public ?string $remindees = null;
    
    /**
     * reminder_choice
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListReminderChoice $reminderChoice
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=reminder_choice')]
    public ?MeldListReminderChoice $reminderChoice = null;
    
    /**
     * reminder_gte
     * 
     * @var ?string $reminderGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=reminder_gte')]
    public ?string $reminderGte = null;
    
    /**
     * reminder_lte
     * 
     * @var ?string $reminderLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=reminder_lte')]
    public ?string $reminderLte = null;
    
    /**
     * scheduled__gte
     * 
     * @var ?string $scheduledGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=scheduled__gte')]
    public ?string $scheduledGte = null;
    
    /**
     * scheduled__interval
     * 
     * @var ?string $scheduledInterval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=scheduled__interval')]
    public ?string $scheduledInterval = null;
    
    /**
     * scheduled__lte
     * 
     * @var ?string $scheduledLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=scheduled__lte')]
    public ?string $scheduledLte = null;
    
    /**
     * scheduling
     * 
     * @var ?string $scheduling
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=scheduling')]
    public ?string $scheduling = null;
    
    /**
     * status
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListStatus $status
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?MeldListStatus $status = null;
    
    /**
     * tags
     * 
     * @var ?string $tags
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tags')]
    public ?string $tags = null;
    
    /**
     * tags_ex
     * 
     * @var ?string $tagsEx
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tags_ex')]
    public ?string $tagsEx = null;
    
    /**
     * tpr
     * 
     * @var ?\PropertyMeld\MeldAPI\Models\Operations\MeldListTpr $tpr
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tpr')]
    public ?MeldListTpr $tpr = null;
    
    /**
     * unit
     * 
     * @var ?string $unit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=unit')]
    public ?string $unit = null;
    
    /**
     * updated__gte
     * 
     * @var ?string $updatedGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=updated__gte')]
    public ?string $updatedGte = null;
    
    /**
     * updated__interval
     * 
     * @var ?string $updatedInterval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=updated__interval')]
    public ?string $updatedInterval = null;
    
    /**
     * updated__lte
     * 
     * @var ?string $updatedLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=updated__lte')]
    public ?string $updatedLte = null;
    
    /**
     * updated__offset_lte
     * 
     * @var ?string $updatedOffsetLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=updated__offset_lte')]
    public ?string $updatedOffsetLte = null;
    
    /**
     * vendor_scheduled__gte
     * 
     * @var ?string $vendorScheduledGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=vendor_scheduled__gte')]
    public ?string $vendorScheduledGte = null;
    
    /**
     * vendor_scheduled__interval
     * 
     * @var ?string $vendorScheduledInterval
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=vendor_scheduled__interval')]
    public ?string $vendorScheduledInterval = null;
    
    /**
     * vendor_scheduled__lte
     * 
     * @var ?string $vendorScheduledLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=vendor_scheduled__lte')]
    public ?string $vendorScheduledLte = null;
    
    /**
     * wl__gte
     * 
     * @var ?string $wlGte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=wl__gte')]
    public ?string $wlGte = null;
    
    /**
     * wl__lte
     * 
     * @var ?string $wlLte
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=wl__lte')]
    public ?string $wlLte = null;
    
	public function __construct()
	{
		$this->xPmOrg = 0;
		$this->ackApproval = null;
		$this->assignedToMe = null;
		$this->categories = null;
		$this->commentsGte = null;
		$this->commentsLte = null;
		$this->completedGte = null;
		$this->completedInterval = null;
		$this->completedLte = null;
		$this->createdGte = null;
		$this->createdInterval = null;
		$this->createdLte = null;
		$this->createdOffsetLte = null;
		$this->dueDateChoice = null;
		$this->dueDateGte = null;
		$this->dueDateLte = null;
		$this->everBeenAssigned = null;
		$this->exp = null;
		$this->expS = null;
		$this->filesGte = null;
		$this->filesLte = null;
		$this->hasEstimates = null;
		$this->invoiceS = null;
		$this->limit = null;
		$this->maint = null;
		$this->maintType = null;
		$this->markedCompleteGte = null;
		$this->markedCompleteInterval = null;
		$this->markedCompleteLte = null;
		$this->meldinvoice = null;
		$this->offset = null;
		$this->orderBy = null;
		$this->ownerApproval = null;
		$this->pg = null;
		$this->priority = null;
		$this->project = null;
		$this->projectAssigned = null;
		$this->prop = null;
		$this->rating = null;
		$this->recurring = null;
		$this->recurringMeld = null;
		$this->remindees = null;
		$this->reminderChoice = null;
		$this->reminderGte = null;
		$this->reminderLte = null;
		$this->scheduledGte = null;
		$this->scheduledInterval = null;
		$this->scheduledLte = null;
		$this->scheduling = null;
		$this->status = null;
		$this->tags = null;
		$this->tagsEx = null;
		$this->tpr = null;
		$this->unit = null;
		$this->updatedGte = null;
		$this->updatedInterval = null;
		$this->updatedLte = null;
		$this->updatedOffsetLte = null;
		$this->vendorScheduledGte = null;
		$this->vendorScheduledInterval = null;
		$this->vendorScheduledLte = null;
		$this->wlGte = null;
		$this->wlLte = null;
	}
}
