<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** ever_been_assigned */
enum MeldListEverBeenAssigned: string
{
    case True = 'true';
    case False = 'false';
}
