<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** tpr */
enum MeldListTpr: string
{
    case FALSE = 'false';
    case TRUE = 'true';
}
