<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** categories */
enum MeldListCategories: string
{
    case FOR_RENT_SIGN = 'FOR_RENT_SIGN';
    case EVALUATION = 'EVALUATION';
    case TURNOVER = 'TURNOVER';
    case APPLIANCES = 'APPLIANCES';
    case BLINDS_WINDOW_TREATMENTS = 'BLINDS_WINDOW_TREATMENTS';
    case CIRCUIT_BREAKER = 'CIRCUIT_BREAKER';
    case CLEANING = 'CLEANING';
    case DOORS = 'DOORS';
    case DRIVEWAY = 'DRIVEWAY';
    case DRYWALL = 'DRYWALL';
    case ELECTRICAL = 'ELECTRICAL';
    case EXTERIOR = 'EXTERIOR';
    case FIREPLACE = 'FIREPLACE';
    case FLOORING = 'FLOORING';
    case GARAGE_DOOR = 'GARAGE_DOOR';
    case GARBAGE_DISPOSAL = 'GARBAGE_DISPOSAL';
    case GENERAL = 'GENERAL';
    case HARDWARE = 'HARDWARE';
    case HVAC = 'HVAC';
    case INTERIOR = 'INTERIOR';
    case LANDSCAPING = 'LANDSCAPING';
    case LOCKS = 'LOCKS';
    case OTHER_WORK_CATEGORY = 'OTHER_WORK_CATEGORY';
    case PAINTING = 'PAINTING';
    case OUTSIDE_WATER_SPIGOT = 'OUTSIDE_WATER_SPIGOT';
    case PEST_CONTROL = 'PEST_CONTROL';
    case PLUMBING = 'PLUMBING';
    case CARPENTRY = 'CARPENTRY';
    case POOL = 'POOL';
    case ROOFING = 'ROOFING';
    case SEWER = 'SEWER';
    case SHOWER = 'SHOWER';
    case SIDING = 'SIDING';
    case SMOKE_DETECTOR_CO_DETECTORS = 'SMOKE_DETECTOR_CO_DETECTORS';
    case SOFFIT_FASCIA = 'SOFFIT_FASCIA';
    case STAIRS = 'STAIRS';
    case TOILET = 'TOILET';
    case TOWEL_BARS = 'TOWEL_BARS';
    case VIOLATIONS = 'VIOLATIONS';
    case WASHER_DRYER = 'WASHER_DRYER';
    case WATER_DAMAGE = 'WATER_DAMAGE';
    case WATER_HEATER = 'WATER_HEATER';
    case WATER_SOFTENER = 'WATER_SOFTENER';
    case WINDOWS = 'WINDOWS';
}
