<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/** categories */
enum MeldListCategories: string
{
    case ForRentSign = 'FOR_RENT_SIGN';
    case Evaluation = 'EVALUATION';
    case Turnover = 'TURNOVER';
    case Appliances = 'APPLIANCES';
    case BlindsWindowTreatments = 'BLINDS_WINDOW_TREATMENTS';
    case CircuitBreaker = 'CIRCUIT_BREAKER';
    case Cleaning = 'CLEANING';
    case Doors = 'DOORS';
    case Driveway = 'DRIVEWAY';
    case Drywall = 'DRYWALL';
    case Electrical = 'ELECTRICAL';
    case Exterior = 'EXTERIOR';
    case Fireplace = 'FIREPLACE';
    case Flooring = 'FLOORING';
    case GarageDoor = 'GARAGE_DOOR';
    case GarbageDisposal = 'GARBAGE_DISPOSAL';
    case General = 'GENERAL';
    case Hardware = 'HARDWARE';
    case Hvac = 'HVAC';
    case Interior = 'INTERIOR';
    case Landscaping = 'LANDSCAPING';
    case Locks = 'LOCKS';
    case OtherWorkCategory = 'OTHER_WORK_CATEGORY';
    case Painting = 'PAINTING';
    case OutsideWaterSpigot = 'OUTSIDE_WATER_SPIGOT';
    case PestControl = 'PEST_CONTROL';
    case Plumbing = 'PLUMBING';
    case Carpentry = 'CARPENTRY';
    case Pool = 'POOL';
    case Roofing = 'ROOFING';
    case Sewer = 'SEWER';
    case Shower = 'SHOWER';
    case Siding = 'SIDING';
    case SmokeDetectorCoDetectors = 'SMOKE_DETECTOR_CO_DETECTORS';
    case SoffitFascia = 'SOFFIT_FASCIA';
    case Stairs = 'STAIRS';
    case Toilet = 'TOILET';
    case TowelBars = 'TOWEL_BARS';
    case Violations = 'VIOLATIONS';
    case WasherDryer = 'WASHER_DRYER';
    case WaterDamage = 'WATER_DAMAGE';
    case WaterHeater = 'WATER_HEATER';
    case WaterSoftener = 'WATER_SOFTENER';
    case Windows = 'WINDOWS';
}
