<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


class PingRetrieveResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * $pingRetrieve200ApplicationJSONObject
     * 
     * @var ?array<string, mixed> $pingRetrieve200ApplicationJSONObject
     */
	
    public ?array $pingRetrieve200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->pingRetrieve200ApplicationJSONObject = null;
	}
}
