<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class ResidentUpdateMultipartRequest
{
	#[SpeakeasyMetadata('request:mediaType=multipart/form-data')]
    public \PropertyMeld\MeldAPI\Models\Shared\ResidentInput1 $residentInput1;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->residentInput1 = new \PropertyMeld\MeldAPI\Models\Shared\ResidentInput1();
		$this->id = "";
	}
}
