<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class ResidentPartialUpdateFormRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/x-www-form-urlencoded')]
    public ?\PropertyMeld\MeldAPI\Models\Shared\PatchedResidentInput1 $patchedResidentInput1 = null;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->patchedResidentInput1 = null;
		$this->id = "";
	}
}
