<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


/**
 */
enum SchemaRetrieveFormat: string
{
    case JSON = 'json';
    case YAML = 'yaml';
}
