<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Operations;


class SchemaRetrieveResponse
{
	
    public ?string $body = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * $schemaRetrieve200ApplicationJSONObject
     * 
     * @var ?array<string, mixed> $schemaRetrieve200ApplicationJSONObject
     */
	
    public ?array $schemaRetrieve200ApplicationJSONObject = null;
    
    /**
     * $schemaRetrieve200ApplicationVndOaiOpenapiPlusJsonObject
     * 
     * @var ?array<string, mixed> $schemaRetrieve200ApplicationVndOaiOpenapiPlusJsonObject
     */
	
    public ?array $schemaRetrieve200ApplicationVndOaiOpenapiPlusJsonObject = null;
    
	public function __construct()
	{
		$this->body = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->schemaRetrieve200ApplicationJSONObject = null;
		$this->schemaRetrieve200ApplicationVndOaiOpenapiPlusJsonObject = null;
	}
}
