<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class Address
{
	#[\JMS\Serializer\Annotation\SerializedName('city')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $city;
    
	#[\JMS\Serializer\Annotation\SerializedName('country')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $country = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('county_province')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $countyProvince;
    
	#[\JMS\Serializer\Annotation\SerializedName('line_1')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $line1;
    
	#[\JMS\Serializer\Annotation\SerializedName('line_2')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $line2 = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('line_3')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $line3 = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('postcode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $postcode;
    
	public function __construct()
	{
		$this->city = "";
		$this->country = null;
		$this->countyProvince = "";
		$this->line1 = "";
		$this->line2 = null;
		$this->line3 = null;
		$this->postcode = "";
	}
}
