<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class Contact
{
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     * 
     * @var ?string $businessPhone
     */
	#[\JMS\Serializer\Annotation\SerializedName('business_phone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $businessPhone = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('business_phone_ext')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $businessPhoneExt = null;
    
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     * 
     * @var ?string $cellPhone
     */
	#[\JMS\Serializer\Annotation\SerializedName('cell_phone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cellPhone = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('cell_phone_ext')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $cellPhoneExt = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('fax')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fax = null;
    
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     * 
     * @var ?string $homePhone
     */
	#[\JMS\Serializer\Annotation\SerializedName('home_phone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $homePhone = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('home_phone_ext')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $homePhoneExt = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('primary_email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $primaryEmail = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('secondary_email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $secondaryEmail = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('tertiary_email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tertiaryEmail = null;
    
	public function __construct()
	{
		$this->businessPhone = null;
		$this->businessPhoneExt = null;
		$this->cellPhone = null;
		$this->cellPhoneExt = null;
		$this->fax = null;
		$this->homePhone = null;
		$this->homePhoneExt = null;
		$this->primaryEmail = null;
		$this->secondaryEmail = null;
		$this->tertiaryEmail = null;
	}
}
