<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class EstimateSerializerDetailOutput
{
	#[\JMS\Serializer\Annotation\SerializedName('approval_requested')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $approvalRequested = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('date_accepted')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $dateAccepted;
    
	#[\JMS\Serializer\Annotation\SerializedName('days_to_complete')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $daysToComplete = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('days_until_start')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $daysUntilStart = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('deadline')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $deadline = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('estimate_meld')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $estimateMeld;
    
	#[\JMS\Serializer\Annotation\SerializedName('estimate_status')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\EstimateStatusEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?EstimateStatusEnum $estimateStatus = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('get_vendor_email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $getVendorEmail;
    
	#[\JMS\Serializer\Annotation\SerializedName('get_vendor_invite_email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $getVendorInviteEmail;
    
	#[\JMS\Serializer\Annotation\SerializedName('get_vendor_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $getVendorName;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
    /**
     * $lineItems
     * 
     * @var array<int> $lineItems
     */
	#[\JMS\Serializer\Annotation\SerializedName('line_items')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    public array $lineItems;
    
	#[\JMS\Serializer\Annotation\SerializedName('notes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $notes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('original_meld')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $originalMeld;
    
	#[\JMS\Serializer\Annotation\SerializedName('pm_fee')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pmFee = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('servicer')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $servicer = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('total')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $total;
    
	#[\JMS\Serializer\Annotation\SerializedName('vendor')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $vendor;
    
	public function __construct()
	{
		$this->approvalRequested = null;
		$this->dateAccepted = new \DateTime();
		$this->daysToComplete = null;
		$this->daysUntilStart = null;
		$this->deadline = null;
		$this->estimateMeld = 0;
		$this->estimateStatus = null;
		$this->getVendorEmail = "";
		$this->getVendorInviteEmail = "";
		$this->getVendorName = "";
		$this->id = 0;
		$this->lineItems = [];
		$this->notes = null;
		$this->originalMeld = 0;
		$this->pmFee = null;
		$this->servicer = null;
		$this->total = "";
		$this->vendor = 0;
	}
}
