<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum HubAccessLevelEnum: string
{
    case DIRECT_ONLY = 'DIRECT_ONLY';
    case ALL_NOTIFICATIONS = 'ALL_NOTIFICATIONS';
    case INVITED_TO_HUB = 'INVITED_TO_HUB';
    case HUB_ACCESS = 'HUB_ACCESS';
}
