<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum HubAccessLevelEnum: string
{
    case DirectOnly = 'DIRECT_ONLY';
    case AllNotifications = 'ALL_NOTIFICATIONS';
    case InvitedToHub = 'INVITED_TO_HUB';
    case HubAccess = 'HUB_ACCESS';
}
