<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class MeldListViewInHouseMeldServicer
{
	#[\JMS\Serializer\Annotation\SerializedName('agent')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldListViewManagementAgent')]
    public MeldListViewManagementAgent $agent;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	public function __construct()
	{
		$this->agent = new \PropertyMeld\MeldAPI\Models\Shared\MeldListViewManagementAgent();
		$this->id = 0;
	}
}
