<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class MeldListViewUnit
{
	#[\JMS\Serializer\Annotation\SerializedName('apartment')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $apartment = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('approval_currency_limit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $approvalCurrencyLimit = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('building')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $building = null;
    
    /**
     * $createBy
     * 
     * @var ?array<string, mixed> $createBy
     */
	#[\JMS\Serializer\Annotation\SerializedName('create_by')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $createBy = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $created;
    
	#[\JMS\Serializer\Annotation\SerializedName('department')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $department = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('display_address')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldListViewUnitDisplayAddress')]
    public MeldListViewUnitDisplayAddress $displayAddress;
    
	#[\JMS\Serializer\Annotation\SerializedName('floor')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $floor = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('is_active')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isActive = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('prop')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldListViewProperty')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MeldListViewProperty $prop = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('room')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $room = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('suite')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $suite = null;
    
    /**
     * $supplementalData
     * 
     * @var ?array<string, mixed> $supplementalData
     */
	#[\JMS\Serializer\Annotation\SerializedName('supplemental_data')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $supplementalData = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $unit = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit_address')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $unitAddress = null;
    
    /**
     * $updateBy
     * 
     * @var ?array<string, mixed> $updateBy
     */
	#[\JMS\Serializer\Annotation\SerializedName('update_by')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $updateBy = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updated;
    
	public function __construct()
	{
		$this->apartment = null;
		$this->approvalCurrencyLimit = null;
		$this->building = null;
		$this->createBy = null;
		$this->created = new \DateTime();
		$this->department = null;
		$this->displayAddress = new \PropertyMeld\MeldAPI\Models\Shared\MeldListViewUnitDisplayAddress();
		$this->floor = null;
		$this->id = 0;
		$this->isActive = null;
		$this->prop = null;
		$this->room = null;
		$this->suite = null;
		$this->supplementalData = null;
		$this->unit = null;
		$this->unitAddress = null;
		$this->updateBy = null;
		$this->updated = new \DateTime();
	}
}
