<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class MeldInvoiceListMeld
{
	#[\JMS\Serializer\Annotation\SerializedName('brief_description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $briefDescription;
    
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $created;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('prop')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldInvoiceListProperty')]
    public MeldInvoiceListProperty $prop;
    
	#[\JMS\Serializer\Annotation\SerializedName('reference_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $referenceId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldInvoiceListViewUnit')]
    public MeldInvoiceListViewUnit $unit;
    
	public function __construct()
	{
		$this->briefDescription = "";
		$this->created = new \DateTime();
		$this->id = 0;
		$this->prop = new \PropertyMeld\MeldAPI\Models\Shared\MeldInvoiceListProperty();
		$this->referenceId = null;
		$this->unit = new \PropertyMeld\MeldAPI\Models\Shared\MeldInvoiceListViewUnit();
	}
}
