<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class MeldInvoiceListViewUnit
{
	#[\JMS\Serializer\Annotation\SerializedName('apartment')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $apartment = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('building')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\BaseBuilding')]
    public BaseBuilding $building;
    
	#[\JMS\Serializer\Annotation\SerializedName('department')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $department = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('display_address')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldInvoiceListDisplayAddress')]
    public MeldInvoiceListDisplayAddress $displayAddress;
    
	#[\JMS\Serializer\Annotation\SerializedName('floor')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\BaseFloor')]
    public BaseFloor $floor;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('prop')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldInvoiceListProperty')]
    public MeldInvoiceListProperty $prop;
    
	#[\JMS\Serializer\Annotation\SerializedName('room')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $room = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('suite')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $suite = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $unit = null;
    
	public function __construct()
	{
		$this->apartment = null;
		$this->building = new \PropertyMeld\MeldAPI\Models\Shared\BaseBuilding();
		$this->department = null;
		$this->displayAddress = new \PropertyMeld\MeldAPI\Models\Shared\MeldInvoiceListDisplayAddress();
		$this->floor = new \PropertyMeld\MeldAPI\Models\Shared\BaseFloor();
		$this->id = 0;
		$this->prop = new \PropertyMeld\MeldAPI\Models\Shared\MeldInvoiceListProperty();
		$this->room = null;
		$this->suite = null;
		$this->unit = null;
	}
}
