<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class MeldExpendituresListMeld
{
	#[\JMS\Serializer\Annotation\SerializedName('assigned')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $assigned = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('assigner')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $assigner;
    
	#[\JMS\Serializer\Annotation\SerializedName('brief_description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $briefDescription;
    
	#[\JMS\Serializer\Annotation\SerializedName('completion_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $completionDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('completion_notes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $completionNotes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $created;
    
	#[\JMS\Serializer\Annotation\SerializedName('creator')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $creator;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('due_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $dueDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('has_pets')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $hasPets = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('has_registered_tenant')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $hasRegisteredTenant = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('is_active')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isActive = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('maintenance_notes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $maintenanceNotes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('management')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $management;
    
	#[\JMS\Serializer\Annotation\SerializedName('management_agent_closer')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $managementAgentCloser = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('manager_cancellation_reason')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $managerCancellationReason = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('manager_cancelled')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $managerCancelled = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('manager_canceller')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $managerCanceller = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('marked_complete')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $markedComplete = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('meld_group')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $meldGroup;
    
	#[\JMS\Serializer\Annotation\SerializedName('notify_owner')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $notifyOwner = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('parent')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $parent = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('pets')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $pets = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('priority')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\PriorityEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PriorityEnum $priority = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('project')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $project = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('prop')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListProperty')]
    public MeldExpendituresListProperty $prop;
    
	#[\JMS\Serializer\Annotation\SerializedName('reason_cannot_complete')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $reasonCannotComplete = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('recurring_meld')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $recurringMeld = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('reference_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $referenceId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('reviewing_tenant')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $reviewingTenant = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('started')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $started = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\Status5c6Enum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Status5c6Enum $status = null;
    
    /**
     * $tags
     * 
     * @var array<int> $tags
     */
	#[\JMS\Serializer\Annotation\SerializedName('tags')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    public array $tags;
    
	#[\JMS\Serializer\Annotation\SerializedName('tenant_canceller')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $tenantCanceller = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('tenant_presence_required')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $tenantPresenceRequired = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('tenant_rating')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $tenantRating = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('tenant_review')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tenantReview = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('tenant_review_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $tenantReviewDate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListUnit')]
    public MeldExpendituresListUnit $unit;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updated;
    
	#[\JMS\Serializer\Annotation\SerializedName('vendor_closer')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $vendorCloser = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('work_category')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\WorkCategoryEnum>')]
    public WorkCategoryEnum $workCategory;
    
	#[\JMS\Serializer\Annotation\SerializedName('work_location')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workLocation;
    
	public function __construct()
	{
		$this->assigned = null;
		$this->assigner = 0;
		$this->briefDescription = "";
		$this->completionDate = null;
		$this->completionNotes = null;
		$this->created = new \DateTime();
		$this->creator = 0;
		$this->description = null;
		$this->dueDate = null;
		$this->hasPets = null;
		$this->hasRegisteredTenant = null;
		$this->id = 0;
		$this->isActive = null;
		$this->maintenanceNotes = null;
		$this->management = 0;
		$this->managementAgentCloser = null;
		$this->managerCancellationReason = null;
		$this->managerCancelled = null;
		$this->managerCanceller = null;
		$this->markedComplete = null;
		$this->meldGroup = 0;
		$this->notifyOwner = null;
		$this->parent = null;
		$this->pets = null;
		$this->priority = null;
		$this->project = null;
		$this->prop = new \PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListProperty();
		$this->reasonCannotComplete = null;
		$this->recurringMeld = null;
		$this->referenceId = null;
		$this->reviewingTenant = null;
		$this->started = null;
		$this->status = null;
		$this->tags = [];
		$this->tenantCanceller = null;
		$this->tenantPresenceRequired = null;
		$this->tenantRating = null;
		$this->tenantReview = null;
		$this->tenantReviewDate = null;
		$this->unit = new \PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListUnit();
		$this->updated = new \DateTime();
		$this->vendorCloser = null;
		$this->workCategory = \PropertyMeld\MeldAPI\Models\Shared\WorkCategoryEnum::FOR_RENT_SIGN;
		$this->workLocation = "";
	}
}
