<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class MeldExpendituresListViewSerializerDetail
{
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $amount;
    
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $created;
    
    /**
     * $expendituresLineItems
     * 
     * @var array<\PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListLineItem> $expendituresLineItems
     */
	#[\JMS\Serializer\Annotation\SerializedName('expenditures_line_items')]
    #[\JMS\Serializer\Annotation\Type('array<PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListLineItem>')]
    public array $expendituresLineItems;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('meld')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListMeld')]
    public MeldExpendituresListMeld $meld;
    
	#[\JMS\Serializer\Annotation\SerializedName('notes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $notes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\StatusD0bEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StatusD0bEnum $status = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updated;
    
	public function __construct()
	{
		$this->amount = "";
		$this->created = new \DateTime();
		$this->expendituresLineItems = [];
		$this->id = 0;
		$this->meld = new \PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListMeld();
		$this->notes = null;
		$this->status = null;
		$this->updated = new \DateTime();
	}
}
