<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum MethodEnum: string
{
    case CASH = 'CASH';
    case ACH = 'ACH';
    case CHECK = 'CHECK';
    case CC = 'CC';
}
