<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum MethodEnum: string
{
    case Cash = 'CASH';
    case Ach = 'ACH';
    case Check = 'CHECK';
    case Cc = 'CC';
}
