<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class NotificationSettingsInput
{
	#[\JMS\Serializer\Annotation\SerializedName('incoming_meld_frequency')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\IncomingMeldFrequencyEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?IncomingMeldFrequencyEnum $incomingMeldFrequency = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('sms_notifications')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $smsNotifications = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('successful_meld_frequency')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\SuccessfulMeldFrequencyEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SuccessfulMeldFrequencyEnum $successfulMeldFrequency = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('timezone')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\TimezoneEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TimezoneEnum $timezone = null;
    
	public function __construct()
	{
		$this->incomingMeldFrequency = null;
		$this->smsNotifications = null;
		$this->successfulMeldFrequency = null;
		$this->timezone = null;
	}
}
