<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class PatchedResidentInput1
{
	#[SpeakeasyMetadata('form:name=address,json=true')]
    #[SpeakeasyMetadata('multipartForm:name=address,json=true')]
    public mixed $address = null;
    
	#[SpeakeasyMetadata('form:name=contact,json=true')]
    #[SpeakeasyMetadata('multipartForm:name=contact,json=true')]
    public ?Contact $contact = null;
    
	#[SpeakeasyMetadata('form:name=first_name')]
    #[SpeakeasyMetadata('multipartForm:name=first_name')]
    public ?string $firstName = null;
    
    /**
     * Send an invite to the resident to access PropertyMeld
     * 
     * @var ?bool $invite
     */
	#[SpeakeasyMetadata('form:name=invite')]
    #[SpeakeasyMetadata('multipartForm:name=invite')]
    public ?bool $invite = null;
    
	#[SpeakeasyMetadata('form:name=last_name')]
    #[SpeakeasyMetadata('multipartForm:name=last_name')]
    public ?string $lastName = null;
    
	#[SpeakeasyMetadata('form:name=middle_name')]
    #[SpeakeasyMetadata('multipartForm:name=middle_name')]
    public ?string $middleName = null;
    
	#[SpeakeasyMetadata('form:name=notes')]
    #[SpeakeasyMetadata('multipartForm:name=notes')]
    public ?string $notes = null;
    
	#[SpeakeasyMetadata('form:name=notification_settings,json=true')]
    #[SpeakeasyMetadata('multipartForm:name=notification_settings,json=true')]
    public ?NotificationSettingsInput $notificationSettings = null;
    
    /**
     * $units
     * 
     * @var ?array<int> $units
     */
	#[SpeakeasyMetadata('form:name=units')]
    #[SpeakeasyMetadata('multipartForm:name=units')]
    public ?array $units = null;
    
	public function __construct()
	{
		$this->address = null;
		$this->contact = null;
		$this->firstName = null;
		$this->invite = null;
		$this->lastName = null;
		$this->middleName = null;
		$this->notes = null;
		$this->notificationSettings = null;
		$this->units = null;
	}
}
