<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class PatchedPropertyInput
{
	#[\JMS\Serializer\Annotation\SerializedName('city')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=city')]
    #[SpeakeasyMetadata('multipartForm:name=city')]
    public ?string $city = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('country')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=country')]
    #[SpeakeasyMetadata('multipartForm:name=country')]
    public ?string $country = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('county_province')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=county_province')]
    #[SpeakeasyMetadata('multipartForm:name=county_province')]
    public ?string $countyProvince = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('line_1')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=line_1')]
    #[SpeakeasyMetadata('multipartForm:name=line_1')]
    public ?string $line1 = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('line_2')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=line_2')]
    #[SpeakeasyMetadata('multipartForm:name=line_2')]
    public ?string $line2 = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('line_3')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=line_3')]
    #[SpeakeasyMetadata('multipartForm:name=line_3')]
    public ?string $line3 = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('maintenance_notes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=maintenance_notes')]
    #[SpeakeasyMetadata('multipartForm:name=maintenance_notes')]
    public ?string $maintenanceNotes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('other_address_details')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=other_address_details')]
    #[SpeakeasyMetadata('multipartForm:name=other_address_details')]
    public ?string $otherAddressDetails = null;
    
    /**
     * $owners
     * 
     * @var ?array<int> $owners
     */
	#[\JMS\Serializer\Annotation\SerializedName('owners')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=owners')]
    #[SpeakeasyMetadata('multipartForm:name=owners')]
    public ?array $owners = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('postcode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=postcode')]
    #[SpeakeasyMetadata('multipartForm:name=postcode')]
    public ?string $postcode = null;
    
    /**
     * $propertyGroups
     * 
     * @var ?array<int> $propertyGroups
     */
	#[\JMS\Serializer\Annotation\SerializedName('property_groups')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=property_groups')]
    #[SpeakeasyMetadata('multipartForm:name=property_groups')]
    public ?array $propertyGroups = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('property_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=property_name')]
    #[SpeakeasyMetadata('multipartForm:name=property_name')]
    public ?string $propertyName = null;
    
    /**
     * $units
     * 
     * @var ?array<int> $units
     */
	#[\JMS\Serializer\Annotation\SerializedName('units')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=units')]
    #[SpeakeasyMetadata('multipartForm:name=units')]
    public ?array $units = null;
    
	public function __construct()
	{
		$this->city = null;
		$this->country = null;
		$this->countyProvince = null;
		$this->line1 = null;
		$this->line2 = null;
		$this->line3 = null;
		$this->maintenanceNotes = null;
		$this->otherAddressDetails = null;
		$this->owners = null;
		$this->postcode = null;
		$this->propertyGroups = null;
		$this->propertyName = null;
		$this->units = null;
	}
}
