<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class PmAPIProjectDetail
{
    /**
     * $coordinators
     * 
     * @var array<\PropertyMeld\MeldAPI\Models\Shared\ManagementAgent> $coordinators
     */
	#[\JMS\Serializer\Annotation\SerializedName('coordinators')]
    #[\JMS\Serializer\Annotation\Type('array<PropertyMeld\MeldAPI\Models\Shared\ManagementAgent>')]
    public array $coordinators;
    
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $created;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('due_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $dueDate;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
    /**
     * $melds
     * 
     * @var array<int> $melds
     */
	#[\JMS\Serializer\Annotation\SerializedName('melds')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    public array $melds;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('project_type')]
    #[\JMS\Serializer\Annotation\Type('enum<PropertyMeld\MeldAPI\Models\Shared\ProjectTypeEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ProjectTypeEnum $projectType = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('start_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $startDate;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\PmAPIUnit')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PmAPIUnit $unit = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updated;
    
	public function __construct()
	{
		$this->coordinators = [];
		$this->created = new \DateTime();
		$this->description = null;
		$this->dueDate = new \DateTime();
		$this->id = 0;
		$this->melds = [];
		$this->name = "";
		$this->projectType = null;
		$this->startDate = new \DateTime();
		$this->unit = null;
		$this->updated = new \DateTime();
	}
}
