<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum ProjectTypeEnum: string
{
    case OTHER = 'OTHER';
    case RENOVATION = 'RENOVATION';
    case TURN = 'TURN';
    case MITIGATION = 'MITIGATION';
}
