<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum ProjectTypeEnum: string
{
    case Other = 'OTHER';
    case Renovation = 'RENOVATION';
    case Turn = 'TURN';
    case Mitigation = 'MITIGATION';
}
