<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum Status09fEnum: string
{
    case Draft = 'DRAFT';
    case Submitted = 'SUBMITTED';
    case InReview = 'IN_REVIEW';
    case Hold = 'HOLD';
    case Declined = 'DECLINED';
    case Approved = 'APPROVED';
    case Paid = 'PAID';
}
