<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum Status5c6Enum: string
{
    case Open = 'OPEN';
    case ManagerCanceled = 'MANAGER_CANCELED';
    case TenantCanceled = 'TENANT_CANCELED';
    case PendingEstimates = 'PENDING_ESTIMATES';
    case PendingTenantAvailability = 'PENDING_TENANT_AVAILABILITY';
    case PendingMoreVendorAvailability = 'PENDING_MORE_VENDOR_AVAILABILITY';
    case PendingMoreManagementAvailability = 'PENDING_MORE_MANAGEMENT_AVAILABILITY';
    case PendingCompletion = 'PENDING_COMPLETION';
    case Completed = 'COMPLETED';
    case VendorCouldNotComplete = 'VENDOR_COULD_NOT_COMPLETE';
    case MaintenanceCouldNotComplete = 'MAINTENANCE_COULD_NOT_COMPLETE';
    case PendingVendor = 'PENDING_VENDOR';
    case PendingAssignment = 'PENDING_ASSIGNMENT';
}
