<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


enum SuccessfulMeldFrequencyEnum: string
{
    case Immediately = 'IMMEDIATELY';
    case Daily = 'DAILY';
    case Never = 'NEVER';
}
