<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class Unit
{
	#[\JMS\Serializer\Annotation\SerializedName('approval_currency_limit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $approvalCurrencyLimit = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $created;
    
    /**
     * $currentResidents
     * 
     * @var ?array<int> $currentResidents
     */
	#[\JMS\Serializer\Annotation\SerializedName('current_residents')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $currentResidents = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('is_active')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $isActive;
    
	#[\JMS\Serializer\Annotation\SerializedName('maintenance_notes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $maintenanceNotes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('property_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $propertyId;
    
    /**
     * This field indicates the particular dwelling within a larger building or complex. For example, in the address 123 Main St, Unit 302, the unit is 302
     * 
     * @var ?string $unit
     */
	#[\JMS\Serializer\Annotation\SerializedName('unit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $unit = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit_address')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\Address')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Address $unitAddress = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updated;
    
	public function __construct()
	{
		$this->approvalCurrencyLimit = null;
		$this->created = new \DateTime();
		$this->currentResidents = null;
		$this->id = 0;
		$this->isActive = false;
		$this->maintenanceNotes = null;
		$this->propertyId = 0;
		$this->unit = null;
		$this->unitAddress = null;
		$this->updated = new \DateTime();
	}
}
