<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class UnitInput
{
	#[\JMS\Serializer\Annotation\SerializedName('approval_currency_limit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=approval_currency_limit')]
    #[SpeakeasyMetadata('multipartForm:name=approval_currency_limit')]
    public ?string $approvalCurrencyLimit = null;
    
    /**
     * $currentResidents
     * 
     * @var ?array<int> $currentResidents
     */
	#[\JMS\Serializer\Annotation\SerializedName('current_residents')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=current_residents')]
    #[SpeakeasyMetadata('multipartForm:name=current_residents')]
    public ?array $currentResidents = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('maintenance_notes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=maintenance_notes')]
    #[SpeakeasyMetadata('multipartForm:name=maintenance_notes')]
    public ?string $maintenanceNotes = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('property_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[SpeakeasyMetadata('form:name=property_id')]
    #[SpeakeasyMetadata('multipartForm:name=property_id')]
    public int $propertyId;
    
    /**
     * This field indicates the particular dwelling within a larger building or complex. For example, in the address 123 Main St, Unit 302, the unit is 302
     * 
     * @var ?string $unit
     */
	#[\JMS\Serializer\Annotation\SerializedName('unit')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=unit')]
    #[SpeakeasyMetadata('multipartForm:name=unit')]
    public ?string $unit = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('unit_address')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\Address')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=unit_address,json=true')]
    #[SpeakeasyMetadata('multipartForm:name=unit_address,json=true')]
    public ?Address $unitAddress = null;
    
	public function __construct()
	{
		$this->approvalCurrencyLimit = null;
		$this->currentResidents = null;
		$this->maintenanceNotes = null;
		$this->propertyId = 0;
		$this->unit = null;
		$this->unitAddress = null;
	}
}
