<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;

use \PropertyMeld\MeldAPI\Utils\SpeakeasyMetadata;
class VendorInvite
{
	#[\JMS\Serializer\Annotation\SerializedName('company_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=company_name')]
    #[SpeakeasyMetadata('multipartForm:name=company_name')]
    public ?string $companyName = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('company_phone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=company_phone')]
    #[SpeakeasyMetadata('multipartForm:name=company_phone')]
    public ?string $companyPhone = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[SpeakeasyMetadata('form:name=email')]
    #[SpeakeasyMetadata('multipartForm:name=email')]
    public string $email;
    
	#[\JMS\Serializer\Annotation\SerializedName('first_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=first_name')]
    #[SpeakeasyMetadata('multipartForm:name=first_name')]
    public ?string $firstName = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('last_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=last_name')]
    #[SpeakeasyMetadata('multipartForm:name=last_name')]
    public ?string $lastName = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('line_1')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=line_1')]
    #[SpeakeasyMetadata('multipartForm:name=line_1')]
    public ?string $line1 = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('postcode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    #[SpeakeasyMetadata('form:name=postcode')]
    #[SpeakeasyMetadata('multipartForm:name=postcode')]
    public ?string $postcode = null;
    
	public function __construct()
	{
		$this->companyName = null;
		$this->companyPhone = null;
		$this->email = "";
		$this->firstName = null;
		$this->lastName = null;
		$this->line1 = null;
		$this->postcode = null;
	}
}
