<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class VendorAvailabilitySegment
{
	#[\JMS\Serializer\Annotation\SerializedName('assignment_request')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $assignmentRequest;
    
    /**
     * $createBy
     * 
     * @var ?array<string, mixed> $createBy
     */
	#[\JMS\Serializer\Annotation\SerializedName('create_by')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $createBy = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $created;
    
	#[\JMS\Serializer\Annotation\SerializedName('event')]
    #[\JMS\Serializer\Annotation\Type('PropertyMeld\MeldAPI\Models\Shared\BaseEvent')]
    public BaseEvent $event;
    
	#[\JMS\Serializer\Annotation\SerializedName('expired')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $expired = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('reminders_scheduled')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $remindersScheduled = null;
    
    /**
     * $updateBy
     * 
     * @var ?array<string, mixed> $updateBy
     */
	#[\JMS\Serializer\Annotation\SerializedName('update_by')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $updateBy = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updated;
    
	public function __construct()
	{
		$this->assignmentRequest = 0;
		$this->createBy = null;
		$this->created = new \DateTime();
		$this->event = new \PropertyMeld\MeldAPI\Models\Shared\BaseEvent();
		$this->expired = null;
		$this->id = 0;
		$this->remindersScheduled = null;
		$this->updateBy = null;
		$this->updated = new \DateTime();
	}
}
