<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI\Models\Shared;


class WorkEntrySerializerDetail
{
	#[\JMS\Serializer\Annotation\SerializedName('agent')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $agent;
    
	#[\JMS\Serializer\Annotation\SerializedName('checkin')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $checkin = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('checkout')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $checkout = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $created;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('hours')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $hours = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('long_description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $longDescription = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('meld')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $meld;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updated;
    
	#[\JMS\Serializer\Annotation\SerializedName('updater')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $updater;
    
	public function __construct()
	{
		$this->agent = 0;
		$this->checkin = null;
		$this->checkout = null;
		$this->created = new \DateTime();
		$this->description = null;
		$this->hours = null;
		$this->id = 0;
		$this->longDescription = null;
		$this->meld = 0;
		$this->updated = new \DateTime();
		$this->updater = 0;
	}
}
