<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

class Estimates 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * estimatesList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\EstimatesListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\EstimatesListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\EstimatesListResponse
     */
	public function estimatesList(
        \PropertyMeld\MeldAPI\Models\Operations\EstimatesListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\EstimatesListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\EstimatesListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/estimates/');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\EstimatesListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\EstimatesListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedEstimateSerializerListList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedEstimateSerializerListList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * estimatesRetrieve
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\EstimatesRetrieveRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\EstimatesRetrieveSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\EstimatesRetrieveResponse
     */
	public function estimatesRetrieve(
        \PropertyMeld\MeldAPI\Models\Operations\EstimatesRetrieveRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\EstimatesRetrieveSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\EstimatesRetrieveResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/estimates/{id}/', \PropertyMeld\MeldAPI\Models\Operations\EstimatesRetrieveRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\EstimatesRetrieveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->estimateSerializerDetail = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\EstimateSerializerDetailOutput', 'json');
            }
        }

        return $response;
    }
}