<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

class Expenditure 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * expenditureList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\ExpenditureListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\ExpenditureListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\ExpenditureListResponse
     */
	public function expenditureList(
        \PropertyMeld\MeldAPI\Models\Operations\ExpenditureListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\ExpenditureListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\ExpenditureListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/expenditure/');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\ExpenditureListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\ExpenditureListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedMeldExpendituresListViewSerializerListList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedMeldExpendituresListViewSerializerListList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * expenditureRetrieve
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\ExpenditureRetrieveRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\ExpenditureRetrieveSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\ExpenditureRetrieveResponse
     */
	public function expenditureRetrieve(
        \PropertyMeld\MeldAPI\Models\Operations\ExpenditureRetrieveRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\ExpenditureRetrieveSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\ExpenditureRetrieveResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/expenditure/{id}/', \PropertyMeld\MeldAPI\Models\Operations\ExpenditureRetrieveRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\ExpenditureRetrieveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->meldExpendituresListViewSerializerDetail = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\MeldExpendituresListViewSerializerDetail', 'json');
            }
        }

        return $response;
    }
}