<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

class ManagementAgent 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * managementAgentList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentListResponse
     */
	public function managementAgentList(
        \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/management_agent/');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\ManagementAgentListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedManagementAgentSerializerListList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedManagementAgentSerializerListList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * managementAgentRetrieve
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentRetrieveRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentRetrieveSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentRetrieveResponse
     */
	public function managementAgentRetrieve(
        \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentRetrieveRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentRetrieveSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentRetrieveResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/management_agent/{id}/', \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentRetrieveRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\ManagementAgentRetrieveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->managementAgentSerializerDetail = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\ManagementAgentSerializerDetail', 'json');
            }
        }

        return $response;
    }
}