<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

class Meld 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * meldList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\MeldListResponse
     */
	public function meldList(
        \PropertyMeld\MeldAPI\Models\Operations\MeldListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\MeldListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\MeldListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/meld/');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\MeldListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\MeldListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedMeldSerializerListList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedMeldSerializerListList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * meldManagerFilesList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListResponse
     */
	public function meldManagerFilesList(
        \PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/meld/{id}/manager-files/', \PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\MeldManagerFilesListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedPMApiMeldfileList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedPMApiMeldfileList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * meldRetrieve
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldRetrieveRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldRetrieveSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\MeldRetrieveResponse
     */
	public function meldRetrieve(
        \PropertyMeld\MeldAPI\Models\Operations\MeldRetrieveRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\MeldRetrieveSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\MeldRetrieveResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/meld/{id}/', \PropertyMeld\MeldAPI\Models\Operations\MeldRetrieveRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\MeldRetrieveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->meldSerializerDetail = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\MeldSerializerDetailOutput', 'json');
            }
        }

        return $response;
    }
	
    /**
     * meldTenantFilesList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListResponse
     */
	public function meldTenantFilesList(
        \PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/meld/{id}/tenant-files/', \PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\MeldTenantFilesListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedPmAPITenantMeldList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedPmAPITenantMeldList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * meldVendorFilesList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListResponse
     */
	public function meldVendorFilesList(
        \PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/meld/{id}/vendor-files/', \PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\MeldVendorFilesListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedPMApiVendorMeldFileList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedPMApiVendorMeldFileList', 'json');
            }
        }

        return $response;
    }
}