<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

/**
 * MeldAPI - Property Meld API: An API to access data from your Property Meld Account.
 * 
 * @package PropertyMeld\MeldAPI
 * @access public
 */
class MeldAPI
{
	public const SERVERS = [
        /** Property Meld Production Application */
		'https://app.propertymeld.com/',
	];
  	
	public Building $building;
	
	public CheckToken $checkToken;
	
	public Estimates $estimates;
	
	public Expenditure $expenditure;
	
	public Floor $floor;
	
	public Invoice $invoice;
	
	public ManagementAgent $managementAgent;
	
	public ManagerFile $managerFile;
	
	public Meld $meld;
	
	public Owner $owner;
	
	public Ping $ping;
	
	public Project $project;
	
	public Property $property;
	
	public PropertyGroup $propertyGroup;
	
	public Resident $resident;
	
	public ResidentFile $residentFile;
	
	public Schema $schema;
	
	public Unit $unit;
	
	public Vendor $vendor;
	
	public VendorFile $vendorFile;
	
	public VendorInvite $vendorInvite;
	
	public WorkLog $workLog;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return MeldAPIBuilder
	 */
	public static function builder(): MeldAPIBuilder
	{
		return new MeldAPIBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->building = new Building($this->sdkConfiguration);
		
		$this->checkToken = new CheckToken($this->sdkConfiguration);
		
		$this->estimates = new Estimates($this->sdkConfiguration);
		
		$this->expenditure = new Expenditure($this->sdkConfiguration);
		
		$this->floor = new Floor($this->sdkConfiguration);
		
		$this->invoice = new Invoice($this->sdkConfiguration);
		
		$this->managementAgent = new ManagementAgent($this->sdkConfiguration);
		
		$this->managerFile = new ManagerFile($this->sdkConfiguration);
		
		$this->meld = new Meld($this->sdkConfiguration);
		
		$this->owner = new Owner($this->sdkConfiguration);
		
		$this->ping = new Ping($this->sdkConfiguration);
		
		$this->project = new Project($this->sdkConfiguration);
		
		$this->property = new Property($this->sdkConfiguration);
		
		$this->propertyGroup = new PropertyGroup($this->sdkConfiguration);
		
		$this->resident = new Resident($this->sdkConfiguration);
		
		$this->residentFile = new ResidentFile($this->sdkConfiguration);
		
		$this->schema = new Schema($this->sdkConfiguration);
		
		$this->unit = new Unit($this->sdkConfiguration);
		
		$this->vendor = new Vendor($this->sdkConfiguration);
		
		$this->vendorFile = new VendorFile($this->sdkConfiguration);
		
		$this->vendorInvite = new VendorInvite($this->sdkConfiguration);
		
		$this->workLog = new WorkLog($this->sdkConfiguration);
	}
}