<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

class PropertyGroup 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * propertyGroupList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupListResponse
     */
	public function propertyGroupList(
        \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/property_group/');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\PropertyGroupListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedPropertyGroupSerializerListList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedPropertyGroupSerializerListList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * propertyGroupRetrieve
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupRetrieveRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupRetrieveSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupRetrieveResponse
     */
	public function propertyGroupRetrieve(
        \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupRetrieveRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupRetrieveSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupRetrieveResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/property_group/{id}/', \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupRetrieveRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\PropertyGroupRetrieveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->propertyGroupSerializerDetail = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PropertyGroupSerializerDetail', 'json');
            }
        }

        return $response;
    }
}