<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

class Vendor 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * vendorDestroy
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\VendorDestroyRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\VendorDestroySecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\VendorDestroyResponse
     */
	public function vendorDestroy(
        \PropertyMeld\MeldAPI\Models\Operations\VendorDestroyRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\VendorDestroySecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\VendorDestroyResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/vendor/{id}/', \PropertyMeld\MeldAPI\Models\Operations\VendorDestroyRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('DELETE', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\VendorDestroyResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 204) {
        }

        return $response;
    }
	
    /**
     * vendorList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\VendorListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\VendorListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\VendorListResponse
     */
	public function vendorList(
        \PropertyMeld\MeldAPI\Models\Operations\VendorListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\VendorListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\VendorListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/vendor/');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\VendorListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\VendorListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedVendorList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedVendorList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * vendorRetrieve
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\VendorRetrieveRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\VendorRetrieveSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\VendorRetrieveResponse
     */
	public function vendorRetrieve(
        \PropertyMeld\MeldAPI\Models\Operations\VendorRetrieveRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\VendorRetrieveSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\VendorRetrieveResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/vendor/{id}/', \PropertyMeld\MeldAPI\Models\Operations\VendorRetrieveRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\VendorRetrieveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->vendor = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\Vendor', 'json');
            }
        }

        return $response;
    }
}