<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

class VendorInvite 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * vendorInviteCreate
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\VendorInviteCreateRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\VendorInviteCreateSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\VendorInviteCreateResponse
     */
	public function vendorInviteCreate(
        \PropertyMeld\MeldAPI\Models\Operations\VendorInviteCreateRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\VendorInviteCreateSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\VendorInviteCreateResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/vendor_invite/');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "vendorInvite", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\VendorInviteCreateResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 201) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->vendorInvite = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\VendorInvite', 'json');
            }
        }

        return $response;
    }
}