<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace PropertyMeld\MeldAPI;

class WorkLog 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * workLogList
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\WorkLogListRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\WorkLogListSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\WorkLogListResponse
     */
	public function workLogList(
        \PropertyMeld\MeldAPI\Models\Operations\WorkLogListRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\WorkLogListSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\WorkLogListResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/work_log/');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\PropertyMeld\MeldAPI\Models\Operations\WorkLogListRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\WorkLogListResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paginatedWorkEntrySerializerListList = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\PaginatedWorkEntrySerializerListList', 'json');
            }
        }

        return $response;
    }
	
    /**
     * workLogRetrieve
     * 
     * @param \PropertyMeld\MeldAPI\Models\Operations\WorkLogRetrieveRequest $request
     * @param \PropertyMeld\MeldAPI\Models\Operations\WorkLogRetrieveSecurity $security
     * @return \PropertyMeld\MeldAPI\Models\Operations\WorkLogRetrieveResponse
     */
	public function workLogRetrieve(
        \PropertyMeld\MeldAPI\Models\Operations\WorkLogRetrieveRequest $request,
        \PropertyMeld\MeldAPI\Models\Operations\WorkLogRetrieveSecurity $security,
    ): \PropertyMeld\MeldAPI\Models\Operations\WorkLogRetrieveResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v0.0.1/work_log/{id}/', \PropertyMeld\MeldAPI\Models\Operations\WorkLogRetrieveRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = sprintf('speakeasy-sdk/%s %s %s %s', $this->sdkConfiguration->language, $this->sdkConfiguration->sdkVersion, $this->sdkConfiguration->genVersion, $this->sdkConfiguration->openapiDocVersion);
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \PropertyMeld\MeldAPI\Models\Operations\WorkLogRetrieveResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->workEntrySerializerDetail = $serializer->deserialize((string)$httpResponse->getBody(), 'PropertyMeld\MeldAPI\Models\Shared\WorkEntrySerializerDetail', 'json');
            }
        }

        return $response;
    }
}